<<<<<<< HEAD
{% set name = "medscale" %}
=======
<<<<<<< HEAD
{% set name = "medscale" %}
=======
{% set name = "medscale" %}
>>>>>>> fe4962455354c9c11afd9c9806ceda28eb280737
>>>>>>> 64b283ee525ef53c32509882719e74890329b83f
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
<<<<<<< HEAD
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/medscale-{{ version }}.tar.gz
=======
<<<<<<< HEAD
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/medscale-{{ version }}.tar.gz
=======
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/medscale-{{ version }}.tar.gz
>>>>>>> fe4962455354c9c11afd9c9806ceda28eb280737
>>>>>>> 64b283ee525ef53c32509882719e74890329b83f
  sha256: f7802afa41b7edc34adb3128fbadd18ceb2a92521384e57b9d7cbb9aae894ea6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - fvcore
    - grpcio >=1.45.0
    - grpcio-tools
    - iopath
    - numpy <1.23.0
    - pandas
    - protobuf ==3.19.4
    - pympler
    - python >=3.9
    - pyyaml >=5.1
    - scikit-learn >=1.0.2
    - scipy ==1.7.3
    - tensorboard
    - tensorboardx
    - wandb

test:
  imports:
<<<<<<< HEAD
    - medscale
=======
<<<<<<< HEAD
    - medscale
=======
    - medscale
>>>>>>> fe4962455354c9c11afd9c9806ceda28eb280737
>>>>>>> 64b283ee525ef53c32509882719e74890329b83f
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alibaba/medscale
  summary: Federated learning package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rayrayraykk
