use_gpu: True
device: 0
early_stop:
  patience: 5
seed: 2
backend: torch
federate:
  mode: standalone
  total_round_num: 10
  sample_client_num: 10
  make_global_eval: False
  merge_test_data: False
  client_num: 10
  method: local
data:
  root: data/
  type: lung100
  splits:  [0.8,0,0.2]
  batch_size: 16
  num_workers: 0
  splitter: 'lda'
  splitter_args: [{'alpha': 0.3}]
dataloader:
  batch_size: 16
personalization:
  local_update_steps: 1
  lr: 0.5
model:
  type: convnet5
  hidden: 2048
  out_channels: 62
  dropout: 0.0
train:
  local_update_steps: 1
  batch_or_epoch: epoch
  optimizer:
    lr: 0.01
    weight_decay: 0.0
grad:
  grad_clip: 5.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  freq: 1
  metrics: ['acc', 'correct','f1' ]
  best_res_update_round_wise_key: test_loss
