use_gpu: True
device: 0
early_stop:
  patience: 5
seed: 2
backend: torch
federate:
  mode: standalone
  total_round_num: 10
  sample_client_num: 5
  make_global_eval: True
  merge_test_data: False
  client_num: 5
data:
  root: data/
  type: lung
  splits:  [0.6,0.2,0.2]
  batch_size: 1
  subsample: 0.4
  num_workers: 0
  transform: [['ToTensor'], ['Normalize', {'mean': [0.1307], 'std': [0.3081]}]]
  splitter: 'lda'
  splitter_args: [{'alpha': 0.1}]
dataloader:
  batch_size: 1
personalization:
  local_update_steps: 3
  lr: 0.5
  regular_weight: 1
model:
  type: convnet2
  hidden: 2048
  out_channels: 62
  dropout: 0.0
train:
  local_update_steps: 1
  batch_or_epoch: epoch
  optimizer:
    lr: 0.01
    weight_decay: 0.0
grad:
  grad_clip: 5.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  freq: 1
  metrics: ['acc', 'correct']
  best_res_update_round_wise_key: test_loss
wandb:
  name_project: pFL-bench
  name_user: erfansdarzi
  online_track: true
  use: true
